name: whisper-finetune
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - ipykernel
  - jupyter
  - pip
  - ffmpeg
  - libsndfile
  - pysoundfile
  - librosa
  - pytorch=2.5.*
  - torchaudio=2.5.*
  - pytorch-cuda=12.1
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - transformers>=4.38,<5
  - datasets=2.19.1
  - evaluate
  - jiwer
  - accelerate
  - streamlit